### ISSUE TITLE
Functionality to delete objects from the codebundle

### ISSUE THREAD

**Issue by jon-funk** [Peikae3IWaeG/robotgen#10]
After going through the flow a few times, I think adding a delete button would go a long way for first-time users who may accidently add things and want to delete them afterwards. Reseting the entire codebundle could be frustrating for a first user UX

- Button somewhere in the sections pictured below?

![image](https://github.com/Peikae3IWaeG/robotgen/assets/28266570/fdf0bbd4-8532-45e1-b7ec-bc12096a7a78)

**Comment by Peikae3IWaeG** [comment]
Sounds good to me, let's make it a part of the 1st milestone.
