### ISSUE TITLE
Improve UI/UX on issue section

### ISSUE THREAD

**Issue by jon-funk** [Peikae3IWaeG/robotgen#12]
Currently the section is a bit unclear for the flow I should follow - I think a vertical bar seperate with a OR between the 2 sections would go a long way for hinting to the user there's 2 options

Additionally, let's update `Placeholder` to something more intuitive now

![image](https://github.com/Peikae3IWaeG/robotgen/assets/28266570/d458b65b-6544-45a5-8246-8109386af757)

**Comment by Peikae3IWaeG** [comment]
How about making it a part of milestone 2 and putting the `Generate with ChatGPT` input box into a dialog or an accordion?
