### ISSUE TITLE
Simulate endpoint errors

### ISSUE THREAD

**Issue by jon-funk** [Peikae3IWaeG/robotgen#9]
We started switching off old infra late last week so the endpoint is now failing for the simulate endpoint. (Standing up new test+beta infra) 

Considering we have custom prompts anyways it might be ideal to just move to using chatgpt directly for the simulate call - I can ask the team about endpoint in the new infra today

**Comment by Peikae3IWaeG** [comment]
How about moving to OpenAI endpoints like in entire `/gpt` API namespace?

**Comment by jon-funk** [comment]
Yep! That works!
